locales:
    - af
    - an
    - anp
    - ar
    - ast
    - az
    - bg
    - bn
    - bo
    - br
    - bs
    - ca
    - co
    - cs
    - cy
    - da
    - de
    - dsb
    - el
    - en-CA
    - en-GB
    - en-US
    - eo
    - es-AR
    - es-CL
    - es-MX
    - es
    - eu
    - fa
    - fi
    - fr
    - ga-IE
    - gd
    - gl
    - gu-IN
    - he
    - hi-IN
    - hr
    - hsb
    - hu
    - hy-AM
    - ia
    - id
    - is
    - it
    - ja
    - jv
    - ka
    - kab
    - kk
    - km
    - kn
    - ko
    - lo
    - lt
    - lv
    - ml
    - mr
    - ms
    - my
    - nb-NO
    - ne-NP
    - nl
    - nn-NO
    - oc
    - or
    - pa-IN
    - pl
    - pt-BR
    - pt-PT
    - rm
    - ro
    - ru
    - sat-Olck
    - ses
    - sk
    - sl
    - sq
    - su
    - sv-SE
    - ta
    - te
    - th
    - tl
    - tr
    - uk
    - ur
    - uz
    - vi
    - zgh
    - zh-CN
    - zh-TW
locales-with-shorter-context-menu: ["hi-IN", "th", "zh-CN", "zh-TW"]  # These locales have 1 less screenshot. 
usual-number-of-screenshots: 55
